# Generated by Django 4.1.2 on 2022-12-12 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_save', models.FileField(upload_to='exfile')),
            ],
        ),
        migrations.CreateModel(
            name='InFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_raw', models.IntegerField()),
                ('cryptcode', models.CharField(max_length=250, verbose_name='Шифр')),
                ('fsnb', models.CharField(max_length=250, verbose_name='Обоснование (код ФСНБ)')),
                ('mtr', models.CharField(max_length=250, verbose_name='Наименование МТР')),
                ('metric', models.CharField(max_length=50, verbose_name='Ед. измерения')),
                ('all_counts', models.FloatField(default=0, verbose_name='Общее количество')),
                ('price_not_nds', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='цена за ед. без учета НДС')),
                ('index', models.FloatField(default=0, max_length=250)),
                ('price_smeta', models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='Сметная цена')),
                ('nomenclature', models.CharField(max_length=250)),
                ('razdel', models.IntegerField(default=0, max_length=250)),
                ('mtr_count', models.FloatField(default=0, max_length=250)),
                ('price_mtr_for_ed', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('price_mtr_sum', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('materials_price_mtr_sum', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('oborud', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('mtr_count_other', models.FloatField(default=0, max_length=250)),
                ('price_mtr_for_ed_other', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('price_mtr_sum_other', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('materials_price_mtr_sum_other', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('oborud_other', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('mtr_count_orders', models.FloatField(default=0, max_length=250)),
                ('price_mtr_for_ed_orders', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('price_mtr_sum_orders', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('materials_price_mtr_sum_orders', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=30)),
                ('oborud_orders', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('operator', models.CharField(default='None', max_length=120)),
                ('origin_mtr', models.CharField(default='None', max_length=250)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docap.filedata', verbose_name='File')),
            ],
        ),
    ]
